[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/swagger.yaml"]
  
[[redirects]]
  from = "/api-docs/*"
  to = "/.netlify/functions/api/api-docs/:splat"
  status = 200

[[redirects]]
  from = "/api-docs"
  to = "/.netlify/functions/api/api-docs"
  status = 200


# Redirect khusus untuk API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
