name:
  Sync Swagger to gh-pages

  # Trigger workflow saat push ke branch main, hanya untuk perubahan pada swagger.yaml
on:
  push:
    branches: [main]
    paths:
      - "docs/swagger.yaml"

jobs:
  sync-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Checkout swagger.yaml from main
        run: |
          git fetch origin main
          git checkout origin/main -- docs/swagger.yaml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/swagger.yaml
          git commit -m "Sync swagger.yaml from main" || echo "No changes to commit"
          git push origin gh-pages
